security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # InMemory provider (dla testów)
        users_in_memory:
            memory:
                users:
                    admin:
                        password: '%env(APP_ADMIN_PASSWORD)%'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            logout:
                path: /api/logout

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }  # Swagger dostępny dla każdego
        - { path: ^/api, roles: ROLE_USER }
