version: '3.8'

services:  
  db:
    image: postgres:latest
    container_name: symfony_db
    ports:
      - "5433:5432"
    networks:
      - symfony-network
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
      POSTGRES_USER: docker

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: symfony_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - symfony-network

  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    networks:
      - symfony-network
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony-network
    depends_on:
      - php

networks:
  symfony-network:

volumes:
  pg-data:
