services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
      POSTGRES_USER: docker
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
